### ISSUE TITLE
Major Restructuring to v0.2.0

### ISSUE THREAD

**Issue by PseudoBob-Delightus** [PseudoBob-Delightus/fimfic-data#9]
Restructure the program into proper components (Classes, mostly). Other changes will go along with that.

- [ ] #1 . Concerned with making web requests and ensuring response validity. Invalid responses may involve retries and/or skips.
- [ ] #10 . Concerned with taking all the raw web request data and converting it into a useful object mode.
- [ ] #11 . Concerned with taking the object model and saving it in a database.
- [ ] #12 . Concerned with invoking the Web Request Handler, Data Processor, and Database Handler, in order and with the proper linking and data transformation (if required) between steps.
- [x] #14 . Concerned with keeping a task running consistently at the correct time. (May be as simple as 'wait until X')
- [ ] #13 . Concerned with running the Scraper Task running at its scheduled time, indefinitely.
